### DISCUSSION TITLE
Add git binary to Docker image

### DISCUSSION THREAD

**Discussion by ossinkine** [kamilkisiela/graphql-inspector#1628] [General]
The documentation says it can be used in the CI the simple way:
```
# Inside the .circleci/config.yml file:
version: 2
jobs:
  build:
    docker:
      - image: kamilkisiela/graphql-inspector
    steps:
      - checkout
      - run:
          name: GraphQL Inspector
          command: 'graphql-inspector diff "git:origin/master:./schema.graphql" "schema.graphql"'
```
But this example fails with an error `git: command not found` (I've tested on Gitlab CI, not Circle CI, but it doesn't matter), so I suggest to install the git binary in the `kamilkisiela/graphql-inspector` image
