### DISCUSSION TITLE
Add support for path pattern in GitHub Action schema input

### DISCUSSION THREAD

**Discussion by softprops** [kamilkisiela/graphql-inspector#1745] [General]
I have a setup where we keep multiple .graphql files and are then stitched together this is problematic as the current graphql inspector GitHub action only supports  a single schema at a time. In addition to introducing repetition in my workflow file I also run into cases where a type defined to in a common .graphql file is referred to in another

What I'd like to be able to do is to leverage a path pattern in the `schema` input instead which will consolidate then evaluate any schema changes in aggregate

```yaml
- name: Inspect Schemas
   uses: kamilkisiela/graphql-inspector@master
   with:
      github-token: ${{ secrets.GITHUB_TOKEN }}
       schema: 'master:packages/graphql-api/src/typeDefs/*.graphql'
```

This would solve both the repetition as well as the current limitation of graphql inspector not being able to resolve types defined in other files.
