### DISCUSSION TITLE
Is it possible to add headers to the endpoint for a github action?

### DISCUSSION THREAD

**Discussion by tjoskar** [kamilkisiela/graphql-inspector#2055] [Q&A]
Hi,

I need to include some custom headers when fetching the schema. Is the possible in the github action today?
When I try with the following config:
```yml
- name: 🗳️ Validate schema
  uses: kamilkisiela/graphql-inspector@master
  with:
    schema: "schema/graphql.schema.json"
    endpoint:
      url: "http://localhost:3001/graphql"
      method: "POST"
      headers:
        myCustomHeader: true
      annotations: true
      fail-on-breaking: false
```
I'm getting the error "The workflow is not valid. .github/workflows/build.yml (Line: 69, Col: 13): A mapping was not expected"
Line 69 is `endpoint:`. So I guess the Github action only accepts a URL? Would it be possible to accept headers as well?
