### DISCUSSION TITLE
Failed to load 'schema.graphqls'

### DISCUSSION THREAD

**Discussion by ravar17** [kamilkisiela/graphql-inspector#2572] [General]
Hi, 

I would like to use Graphql inspector on Java, Graphql Project. 

My schema file is at "src\main\resources\schema.graphqls", what path and schema value I shoul use in my configuration file.

I am using Github Action way to detect the schema changes and send notification to SLACK.. 

Below are my configurations.

.github\workflows\graphql-inspect.yml
```

name: Schema Validation
 
on: [push]
 
jobs:
  test:
    name: Check Schema
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout
        uses: actions/checkout@master
 
      - uses: kamilkisiela/graphql-inspector@master
        with:
          schema: 'master:/src/main/resources/schema.graphqls'
```

`

.github\graphql-inspector.yml

```
_schema: 'schema.graphqls'
branch: master

notifications:
  slack: 'https://hooks.slack.com/services/TMEYYTBJ4/BYYYHC6U8BE/pRBdnW****************'
diff: true
```

I am getting the below error, If I am trying to Create the PR request... 

![image](https://github.com/kamilkisiela/graphql-inspector/assets/134925809/2204da8a-67e5-4d70-9b81-ed9756d9c6cd)
