### ISSUE TITLE
Support many environments

### ISSUE THREAD

**Issue by kamilkisiela** [kamilkisiela/graphql-inspector#1424]
Right now Inspector compares schemas only against a single branch (usually master). 

Allow to define environments:

```yaml
env:
  production: master
  staging: develop
schema: schema.graphql
```

Implementation:
- [x] use `push` event to check the target branch
- [x] request for `push` events access
- [x] diff against the target branch
- [x] Make sure its backwards-compatible
