### ISSUE TITLE
Managing unrelated PRs

### ISSUE THREAD

**Issue by kamilkisiela** [kamilkisiela/graphql-inspector#1432]
Pull Requests that target to branches different than those defined in configuration are controlled within `others` section. It lets you not to fail their GitHub Checks on breaking changes.

```yaml
others:
  diff:
    failOnBreaking: false
```
