### ISSUE TITLE
[Github Marketplace App] Failing to load the source schema

### ISSUE THREAD

**Issue by madiodio** [kamilkisiela/graphql-inspector#1447]
Hi there, first would like to say this is a wonderful tool.

Just tried to install the Github Marketplace but it's failing on the build with:
**Failed to complete schema check**
__ERROR: Failed to load 'schema.graphql' (ref: *)__

This seems like it cannot find the file **schema.graphql** which is weird because the file exists in the root folder.

I wonder if this is due to having multiple environments set up. I unfortunately can't put together a repo to reproduce because of the structure of the project but tried my best to reproduce the gist of the config that I have.

- **.graphql-inspector.yaml**
```yaml
schema: "schema.graphql"

notifications:
  slack: "<Slack webhook url>"

env:
  production:
    branch: "master"
    endpoint:
      url: "<production endpoint url>"
      method: "POST"
    diff:
      failOnBreaking: true
  development:
    branch: "develop"
    endpoint:
      url: "<development endpoint url>"
      method: "POST"
````

- **.package.json**
```json
...
"scripts:' {
	"generate:schema": "graphql-inspector introspect \"./lib/**/*.graphql\" --write schema.graphql"
}
...
```

- **Branches on the repo** : both **develop** and **master** exist with the same schema.graphql generated at the root.

Let me know if you need additional details.

**_Update_**:
I dig in the codebase and found this is what's throwing
https://github.com/kamilkisiela/graphql-inspector/blob/6dd6a02b987d922927d153115dc2be0d01e14efb/packages/github/src/helpers/loaders.ts#L67

Does the presence of the * in (ref: *) means it can't find the targeted branch ?
