### ISSUE TITLE
GitHub Actions: schema.graphql in subdirectory

### ISSUE THREAD

**Issue by rowi1de** [kamilkisiela/graphql-inspector#1488]
Hey @kamilkisiela,

not 100% sure if config bug or not supported: 

**Describe the bug**
- Configure the GitHub Action to a path
```yml

  validate-graphql:
    name: Validate GraphQL
    runs-on: ubuntu-18.04
    timeout-minutes: 5
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: graphql-inspector
        uses: kamilkisiela/graphql-inspector@master
        if: always()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          schema: 'master:schema/local/schema.graphql'
          annotations: true

```

**Expected behavior**
- Validation of Schema in Subpath Works

**Additional context**
````
Query master:schema/local/schema.graphql from org/repo
{ repository: { object: null } }
Error: result.repository.object.text is null
    at /home/runner/work/_actions/kamilkisiela/graphql-inspector/master/action/index.js:1:774237
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/_actions/kamilkisiela/graphql-inspector/master/action/index.js:1:436145)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
##[error]Failed to load 'schema/local/schema.graphql' (ref: master)

```

**Comment by kamilkisiela** [comment]
If it doesn't work it's definitely a bug

**Comment by kamilkisiela** [comment]
@rowi1de  Is `schema/local/schema.graphql` available on `master`?

**Comment by rowi1de** [comment]
> @rowi1de is `schema/local/schema.graphql` available on `master`?

Yes, does it work for you?

**Comment by kamilkisiela** [comment]
It does but on GitHub App, in Action the loading logic is similar so it should there too. I'm checking Action right now.

**Comment by kamilkisiela** [comment]
@rowi1de https://github.com/kamilkisiela/graphql-inspector-repro-1488/pull/1 could you create a reproduction maybe?

**Comment by rowi1de** [comment]
https://github.com/kamilkisiela/graphql-inspector-repro-1488/pull/2/checks?check_run_id=690068801 doesn't seem to work on "pull_request" event.
That's also the difference to my use case

**Comment by rowi1de** [comment]
Switched to "push" trigger and getting the same 
`##[error]Failed to load 'schema/local/schema.graphql' (ref: master)`


```yaml
name: GraphQL Inspector
on:
  push:
    branches-ignore: 
      - master

jobs:

  graphql-inspector:
    name: Trigger GraphQL Inspector
    runs-on: ubuntu-18.04
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.1
        
      - name: graphql-inspector
        uses: kamilkisiela/graphql-inspector@v2.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          schema: 'master:schema/local/schema.graphql'
          annotations: true

```
