### ISSUE TITLE
GitHub Action doesn't work with introspection result

### ISSUE THREAD

**Issue by BlueHotDog** [kamilkisiela/graphql-inspector#1769]
While trying to run the github action like so:
```yaml
            - uses: kamilkisiela/graphql-inspector@master
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  schema: "master:packages/app/graphql_schema.json"
```
I get the following error:
```
Run kamilkisiela/graphql-inspector@master
  with:
    github-token: ***
    schema: master:packages/app/graphql_schema.json
  env:
    MIX_ENV: test
GraphQL Inspector started
Ref: a7538d6b4ad0ce53ba6a23cccfb46f60e04d7b88
Commit SHA: e80a1e94c6a96114f39e325dd258624f379a19f4
Creating a check named "GraphQL Inspector"
Check ID: 1316971861
Query buh:packages/app/graphql_schema.json from we_are/we_are_repo
Got both sources
Error: Syntax Error: Expected Name, found String "__schema".
```

While running locally using same files via the cli, no errors and everything works.

**To Reproduce**
Not sure how i can help

**Expected behavior**

No errors

**Environment:**

- OS: Ubuntu latest
- `@graphql-inspector/...`: Master
- `graphql`:  Absinthe
- NodeJS: Not relevant

**Additional context**
