### ISSUE TITLE
Github Action fails when using endpoint + annotations

### ISSUE THREAD

**Issue by aleccool213** [kamilkisiela/graphql-inspector#1806]
**Describe the bug**

Tried a few different versions and found that when I ran this github action with `annotations: true`, it fails.

**To Reproduce**

1. Run this github action:

```yml
name: GraphQL Inspector

on: [pull_request]

jobs:
  test:
    name: Check Schema
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@master
      
      - uses: kamilkisiela/graphql-inspector@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          name: 'Check Production Schema'
          schema: './services/gateway/schema.graphql'
          endpoint: '<YOUR_PRD_ENDPOINT>/graphql'
          annotations: true
```

2. Get this output

```
Run kamilkisiela/graphql-inspector@master
GraphQL Inspector started
Ref: <ref>
Commit SHA: <commit sha>
Creating a check named "Check Staging Schema"
Check ID: 1519028239
Got both sources
Built both schemas
Start comparing schemas
Changes: 32
Conclusion: failure
Updating check: 1519028239
Error: Invalid request.

"path" wasn't supplied.
"path" wasn't supplied.
"path" wasn't supplied.
"path" wasn't supplied.
"path" wasn't supplied.
"path" wasn't supplied.
"path" wasn't supplied.
"path" wasn't supplied.
"path" wasn't supplied.
"path" wasn't supplied.
"path" wasn't supplied.
"path" wasn't supplied.
"path" wasn't supplied.
"path" wasn't supplied.
"path" wasn't supplied.
"path" wasn't supplied.
"path" wasn't supplied.
"path" wasn't supplied.
"path" wasn't supplied.
"path" wasn't supplied.
"path" wasn't supplied.
"path" wasn't supplied.
"path" wasn't supplied.
"path" wasn't supplied.
"path" wasn't supplied.
"path" wasn't supplied.
"path" wasn't supplied.
"path" wasn't supplied.
"path" wasn't supplied.
"path" wasn't supplied.
"path" wasn't supplied.
"path" wasn't supplied.
Updating check: 1519028239
Error: Invalid config. Failed to add annotation
Error: Invalid config. Failed to add annotation
```

**Expected behavior**

**Environment:**

- OS:
- `@graphql-inspector/...`:
- `graphql`:
- NodeJS:

**Additional context**
