### ISSUE TITLE
Multiple Github Actions

### ISSUE THREAD

**Issue by tbrannam** [kamilkisiela/graphql-inspector#1823]
**Describe the bug**

In a repository with multiple schemas defined (multiple projects, services, etc) - multiple schemas are being evaluated.

If there are changes in the first schema check - and no changes in the subsequent ones - the report is overwritten and no differences will be reported to the Github actions UI.

**To Reproduce**

- In a Repository with several schemas, 
- Define a GitHub workflow 
- Make a breaking change in the first schema referenced in the workflow.  
- push.

```
name: CI

on: [push]

jobs:
  test:
    name: Check Schema
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Soccer Schema
        uses: kamilkisiela/graphql-inspector@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          schema: 'master:packages/soccer-resolver/schema.graphql'

      - name: Football Schema
        uses: kamilkisiela/graphql-inspector@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          schema: 'master:packages/football-graphql-resolver/schema.graphql'

      - name: Baseball Service Schema
        uses: kamilkisiela/graphql-inspector@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          schema: 'master:packages/baseball-resolver/schema.graphql'

```

**Expected behavior**

The report should rollup or at least concatenate the results - instead of listing zero errors

**Environment:**

- Github Actions

**Additional context**
