### ISSUE TITLE
`Something is wrong with your schema` when PR is behind `main` branch that changed schema

### ISSUE THREAD

**Issue by ruudk** [kamilkisiela/graphql-inspector#1934]
**Describe the bug**

I'm using GraphQL Inspector in GitHub Actions and it's really a life saver 👏 

But there is 1 annoying thing. 

When your PR is not up to date with `main` (it's behind) and `main` changed the GraphQL schema, the PR gets an error: `Something is wrong with your schema`.

I believe this is because the diff is not smart enough. It sees changes between current PR and `main` schema, and therefore thinks something is going to break. 

Shouldn't it compare the PR schema with the last common ancestor on `main`?

I'm using the following GitHub Actions configuration:
```yaml
-   uses: kamilkisiela/graphql-inspector@v2.5.0
     with:
        name: 'GraphQL Inspector'
        github-token: ${{ secrets.github_token }}
        schema: 'main:schema.graphql'
        approve-label: 'breaking graphql change'
```

Am I doing something wrong? 

**To Reproduce**

* Create branch of `main` and don't make any GraphQL changes
* Make a GraphQL change in `main`
* Rerun workflow and see that the branch is now wrong...

**Expected behavior**

No error

**Environment:**

- GitHub Actions
- `kamilkisiela/graphql-inspector@v2.5.0`
