### ISSUE TITLE
Validate for schema that is composed by multiple .graphql files

### ISSUE THREAD

**Issue by dengliu** [kamilkisiela/graphql-inspector#1947]
**Is your feature request related to a problem? Please describe.**

Does graphql-inspector support validating schema that is composed by multiple .graphql files?

**Describe the solution you'd like**

would like a the CLI tool to take in a config file like yaml, where we can specify schema that is composed by multiple .graphql files
E.g.
```
graphql-inspector diff -input input.yaml
```

input.yaml could be something like
```
oldschema:
  - me.graphql
  - friends.graphql
  - post.graphql
newschema:
  - me.graphql
  - friends.graphql
  - post.graphql
  - newadded.graphql
```
**Describe alternatives you've considered**

**Additional context**

we have modularize our graph into multiple fine graphql files and use `extend` verb to stitch them together. E.g.
```
# me.graphql
type me {
  ID: String!
  name: String!
}
```
```
# friends.graphql
extend me {
  friendsID: [String!]!
}
```

**Comment by kamilkisiela** [comment]
@dengliu Hi :) I think we support glob patterns already so you're able to use `*.graphql` as an input for old and new schema. Does it work for you?

In case you need to define a list of files you can do `{a,b,c}.graphql`.

I like your approach so if you think it's better to have a list of files in some kind of config, I'm happy to assist you and help creating a Pull Request

**Comment by thawsitt** [comment]
You can also try merging the schemas first using [@graphql-tools/merge](https://www.npmjs.com/package/@graphql-tools/merge). 

Docs: https://www.graphql-tools.com/docs/schema-merging

**Comment by arxeiss** [comment]
Not sure I did something wrong, but using glob does not work. I get this error then: 
```
ERROR: Failed to load 'schema/console/schema/*.graphql' (ref: develop)
```

This is my `.github/graphql-inspector.yaml`:
```yaml
---
schema: schema/console/schema/*.graphql
env:
    production:
        branch: master
    preview:
        branch: develop

others:
    diff:
        failOnBreaking: false
notifications:
    slack: https://hooks.slack.com/services/***

```
