### ISSUE TITLE
Expected Breaking Change label not working

### ISSUE THREAD

**Issue by vincebrown** [kamilkisiela/graphql-inspector#1971]
**Describe the bug**

After adding the expected breaking change label the check is still failing on an open pr. During original implementation of the action in the repo I had tested this and it was working as expected. The only thing that has changed is after I merged the action we made it a required check on open PRs

**Expected behavior**
When a breaking change is introduced and the PR has the expected breaking change label on it the check should still pass.

**Environment:**
Github Action Implemented:
```yml
name: Schema Validation

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  test:
    name: Check Schema
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - uses: kamilkisiela/graphql-inspector@master
        with:
          schema: 'main:schema.gql'
          approve-label: 'expected breaking change'
```

|Checks|Checks|Checks|
|---|---|--|
|![Screen Shot 2021-07-09 at 1 34 20 PM](https://user-images.githubusercontent.com/7331145/125133851-54bb4f80-e0bb-11eb-91bd-80ec00ebf109.jpg)|![Screen Shot 2021-07-09 at 1 34 09 PM](https://user-images.githubusercontent.com/7331145/125133566-e1194280-e0ba-11eb-8f39-38fb08760f5c.png)|![Screen Shot 2021-07-09 at 1 44 28 PM](https://user-images.githubusercontent.com/7331145/125134346-1d00d780-e0bc-11eb-9762-52ccaef88806.png)|
