### ISSUE TITLE
Github action: Allow globs in schema

### ISSUE THREAD

**Issue by tobiasdiez** [kamilkisiela/graphql-inspector#1978]
**Is your feature request related to a problem? Please describe.**

Often graphql schema's are split in multiple files.

**Describe the solution you'd like**
Allow to specify the schema using a glob as in `schema: main:api/**/*.graphql`.

**Describe alternatives you've considered**

Currently, globs are not supported as the above schema leads to the following error:
```
Error: ENOENT: no such file or directory, open '/home/runner/work/JabRefOnline/JabRefOnline/api/**/*.graphql'
Query main:api/**/*.graphql from JabRef/JabRefOnline
{ repository: { object: null } }
Error: result.repository.object.text is null
    at /home/runner/work/_actions/kamilkisiela/graphql-inspector/v2.6.2/action/index.js:1:357422
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/_actions/kamilkisiela/graphql-inspector/v2.6.2/action/index.js:1:254624)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

It would be also nice if the schema could automatically be picked up from a graphql.config file.

**Additional context**

Moreover, the `schema` field is not documented.

**Comment by lughino** [comment]
@kamilkisiela wouldn't be enough pointing in the documentation that `depth=1` is not allowed if used with github actions and glob?
It's an acceptable tradeoff imo.

**Comment by prescottprue** [comment]
If all code from branches is loaded, then a glob can be passed through to a script like so:

```js
import { mergeTypeDefs } from '@graphql-tools/merge';
import { loadFilesSync } from '@graphql-tools/load-files';
import { print } from 'graphql';
import { writeFileSync } from 'fs';

const typeDefs = mergeTypeDefs(loadFilesSync(`${process.cwd()}/src/**/*.graphql`));
writeFileSync(`${process.cwd()}/combined.graphql`, print(typeDefs))

```
Then in your workflow:

```yaml
      - name: Combine .graphql files (typedefs) for validation
        run: node

      - name: Validate graph changes
        uses: kamilkisiela/graphql-inspector@master
        with:
          approve-label: 'expected-breaking-change'
          schema: 'combined.graphql'
          # Points at stage so that a combined graphql schema file does not need to be git tracked
          endpoint: 'https://graph-api-pilbcz7fiq-uc.run.app'

```

<details>
</details>

**Comment by prescottprue** [comment]
If your are using`endpoint` as a base (assuming you don't want to git track a combined schema file) then you can use merge and load files in a script like so:

**bin/combine-graphql-files.js**
```js
const { mergeTypeDefs } = require('@graphql-tools/merge');
const { loadFilesSync } = require('@graphql-tools/load-files');
const { print } = require('graphql');
const { writeFileSync } = require('fs');

const typeDefs = mergeTypeDefs(loadFilesSync(`${process.cwd()}/src/**/*.graphql`));
writeFileSync(`${process.cwd()}/combined.graphql`, print(typeDefs))
```

Then in call it right before in your workflow and reference the file in graphql-inspector step:

```yaml
      - name: Combine .graphql files for validation
        run: node bin/combine-graphql-files.js

      - name: Validate graph changes
        uses: kamilkisiela/graphql-inspector@master
        with:
          schema: 'combined.graphql'
          endpoint: 'https://yousite.com/graphql
```

<details>
<summary>
Or if you prefer inline instead of referencing a file
</summary>

```yaml
      - name: Combine .graphql files (typedefs) for validation
        uses: actions/github-script@v6
        with:
          script: |
            const { mergeTypeDefs } = require('@graphql-tools/merge');
            const { loadFilesSync } = require('@graphql-tools/load-files');
            const { print } = require('graphql');
            const { writeFileSync } = require('fs');

            const typeDefs = mergeTypeDefs(loadFilesSync(`${process.cwd()}/src/**/*.graphql`));
            writeFileSync(`${process.cwd()}/combined.graphql`, print(typeDefs))

      - name: Validate graph changes
        uses: kamilkisiela/graphql-inspector@master
        with:
          schema: 'combined.graphql'
          endpoint: 'https://yousite.com/graphql
```
</details>


As called out though, for this to be supported in the existing action without using `endpoint` (or tracking your combined graph file) files matching glob would need to be pulled down. All files could be loaded and logic similar to above used if there are limits around pulling only glob files from Github's APIs

**Comment by tobiasdiez** [comment]
Thanks for the suggestion, but my usecase is exactly merging many schema files that are in the same repo.

**Comment by jayzes** [comment]
If it helps, here's a sample config from one of our repos that merges multiple schema files together across different branches:

```yaml
name: GraphQL Inspector
on:
  pull_request:
    paths:
      - 'api/**.gql'
jobs:
  check-schema:
    name: Check Schema for Breaking Changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Base Commit
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.base.sha }}
          path: base_tree

      - name: Checkout PR Commit
        uses: actions/checkout@master
        with:
          path: pr_tree

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
          working-directory: pr_tree

      - name: Compare Schema
        id: compare
        continue-on-error: true
        shell: bash {0}
        working-directory: pr_tree/ruby
        run: |
          oldSchema=$(cat ../../base_tree/api/*.gql)
          newSchema=$(cat ../api/*.gql)
          compareOutput="$(bundle exec schema_comparator verify "$oldSchema" "$newSchema" 2>&1)"
          compareExit=$?
          # https://github.community/t/set-output-truncates-multiline-strings/16852/3
          compareOutput="${compareOutput//'%'/'%25'}"
          compareOutput="${compareOutput//$'\n'/'%0A'}"
          compareOutput="${compareOutput//$'\r'/'%0D'}"
          echo "::set-output name=stdout::$compareOutput"
          exit $compareExit

      - uses: hasura/comment-progress@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          number: ${{ github.event.number }}
          id: gql-changes
          recreate: true
          message: |
            ### GraphQL Changes Summary
            ```
            ${{steps.compare.outputs.stdout}}
            ```

```

It's currently using https://github.com/xuorig/graphql-schema_comparator but could easily be modified to use `graphql-inspector` instead. In our repo structure, schema files live in an `api` folder under the root.
