### ISSUE TITLE
Github Application not reporting status

### ISSUE THREAD

**Issue by larrifax** [kamilkisiela/graphql-inspector#2062]
**Describe the bug**

I've been using the Github Application successfully for a long time, but in the recent two days it stopped working. The check stays forever in the `Expected — Waiting for status to be reported` state. I've tried amending commits to re-trigger it, revoking app permissions & re-instating them, but to no avail.

As I understand, Github Applications have to be hosted somewhere. Could it be that your host is down or the deployment is not working? Or is the problem at my end?

**To Reproduce**

**Expected behavior**

**Environment:**

- GraphQL Inspector application

**Additional context**

**Comment by davidmwhynot** [comment]
I am also experiencing this issue a month later.

**Comment by cramhead** [comment]
We started getting this on Aug 10, 2022, immediately after the last update. I suspect there is a problem with the config. My config is basically the same as https://www.graphql-inspector.com/docs/recipes/environments just with the variable plugged in.
Is there a way to run manually run graphql-inspector from the cli using the config to attempt to find where it's failing?

**Comment by CelsoSantos** [comment]
I installed it yesterday and I don't even see it trying to start, let alone give me an error :(

**Comment by cramhead** [comment]
Did you install it as an action or application? I installed it as an application and was not able to get any information on why things were failing. I did see a comment in the docs to ensure that the schema path has quotes around it, https://www.graphql-inspector.com/docs/api/documents. This example, https://www.graphql-inspector.com/docs/products/github#full-configuration doesn't have quotes, so I'm not sure if this is only for API usage or for passing the yaml file in CI

**Comment by CelsoSantos** [comment]
@cramhead I installed it as an application (I did try the action first, but that seems to fail as well) but my schema is in `.json` format, which I don't see mentioned in the docs, which might be the reason why it fails to even _try_ to start

**Comment by CelsoSantos** [comment]
Isn't this configuration supposed to work?

I have a `graphql-inspector.yaml` at my repos `.github` dir according to the [docs](https://www.the-guild.dev/graphql/inspector/docs/api/documents). Full path would be `.github/graphql-inspector.yaml`:

```yaml
# Enabling / Disabling Schema Diff
diff: true # enabled by default

# Customizing Schema Diff
# diff:
#   # Pull Request annotations (enabled by default)
#   annotations: false
#   # Fail on breaking changes or force SUCCESS when disabled (enabled by default)
#   failOnBreaking: true
# #  # Intercept list of detected changes and decide whether to accept a Pull Request
# #  intercept: '<url>'
#   # Merge Pull Request's branch with the target branch to get the schema (enabled by default)
#   experimental_merge: true
#   # Label to mark Pull Request introducing breaking changes as safe and expected ('approved-breaking-change' by default)
#   approveLabel: approved-breaking-change
#   # Limit a list of changes in summary to max 150
#   summaryLimit: 150

# Notifications (disabled by default)
#notifications:
#  slack: 'webhook url'
#  discord: 'webhook url'
#  webhook: 'webhook url'

# Your main / target branch
branch: master

# A path to a schema file
schema: "./my-project/my-api/src/main/resources/graphql/**/*.graphqls"

## Use live and running endpoint as a source of schema
#endpoint: '<url>'
```

I already have this config on my master branch and on the PR which I'm attempting to execute the GH App but absolutely nothing happens...

**Comment by arxeiss** [comment]
Any updates on this? App is not working for us at all. We disabled and enabled app again.
When I create PR, there is nothing happening at all. Only actions and apps reported are the ones from workflow folders (our own pipelines) or Codecov.

![image](https://user-images.githubusercontent.com/5103109/193574342-971e6c65-3405-43b3-be83-7142306f8763.png)


This is file we have in `.github/graphql-inspector.yaml`

```yaml
---
schema: services/console/schema.graphql
env:
    production:
        branch: master
others:
    diff:
        failOnBreaking: false
notifications:
    slack: https://hooks.slack.com/services/***

```
