### ISSUE TITLE
Github job hangs

### ISSUE THREAD

**Issue by cramhead** [kamilkisiela/graphql-inspector#2101]
**Describe the bug**
There was no schema change in the PR and graphql-inspect shows as complete this view
![image](https://user-images.githubusercontent.com/386035/162036276-70a2c345-473b-40ed-8b4c-37782743f874.png)

Unfortunately, the process doesn't complete in this view
![image](https://user-images.githubusercontent.com/386035/162035971-8cdd4d04-83b8-4f5b-8ae0-125a6c87c3c6.png)

The error message I see when I dig into it is
![image](https://user-images.githubusercontent.com/386035/162035568-0db35aed-3958-4f01-9be5-cc3d004b27dd.png)

The configuration I'm using
```yaml
  graphql-inspector:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run GraphQL Inspector
        uses: kamilkisiela/graphql-inspector@master
        with:
          name: 'Validate against develop'
          schema: 'develop:src/schema.gql'
          approve-label: 'expected-breaking-change' 
```
The develop branch exists, as does the folder `src` with a `schema.gql` file in that folder

**To Reproduce**
This is the first time I've seen this error. The graphql-inspector has worked perfectly until this

**Expected behavior**

The graphql-inspector should pass and complete

**Environment:**

- OS:
- `@graphql-inspector`: The master branch of graphql-inspector
- `graphql`: Nestjs8 with Apollo v3 
- NodeJS: Node16@latest

**Additional context**
I re-ran jobs on other PRs that had previously passed to try to determine if this change was due to the check-in 10hrs ago. I'm not entirely sure it would get the latest, so I don't know if this was a reasonable check. There was no problem in the PR I checked.
