### ISSUE TITLE
Regression: "Failed to find a configuration"

### ISSUE THREAD

**Issue by ramonsnir** [kamilkisiela/graphql-inspector#2105]
**Describe the bug**

We're using Inspector as a GitHub Action. Recently (last week), it stopped working. The action itself runs, but the check is failed and the output is:

```
Failed to complete schema check
ERROR: Failed to find a configuration

https://graphql-inspector.com/docs/products/github#usage
```

**To Reproduce**

Our action:
```
    graphql_inspect:
        runs-on: ubuntu-latest
        permissions:
            checks: write
            contents: read
            statuses: write
        steps:
            - uses: actions/checkout@v3
              with:
                  lfs: true
            - uses: kamilkisiela/graphql-inspector@master
              with:
                  schema: 'main:schema.gql'
```

**Expected behavior**

Configuration (i.e. schema file?) to be found and annotations to be added. Most of our PRs don't even change the schema, so I guess just a green ✅ and no annotations.

**Environment:**

- OS: GitHub Actions (ubuntu?)
- `@graphql-inspector/...`: kamilkisiela/graphql-inspector@master
- `graphql`: 15.8.0
- NodeJS: 16.13.2

**Additional context**

This used to work just fine. We didn't make changes to the workflow in over two weeks, and that change was just upgrading `actions/checkout` from v1 to v3. Before that the workflow hasn't changed in over 2 months.
