### ISSUE TITLE
Allow bold old & new schema to be a file path

### ISSUE THREAD

**Issue by Meemaw** [kamilkisiela/graphql-inspector#2120]
**Describe the bug**
Currently it is possible to define `endpoint` & `schema` parameter to the github action. This combo however doesn't support supplying both from the file system.

Due to authentication reasons, we can't simply fetch our "production" schema as we would have to pass in additional headers (which this action does not support as well).

**Comment by kamilkisiela** [comment]
Not sure if I follow, but when `schema` option is used:

```yaml
- uses: kamilkisiela/graphql-inspector@master
   with:
     schema: 'master:schema.graphql'
```

it gets the `schema.graphql` from the current branch and fetches `schema.graphql` from the `master` branch.
