### ISSUE TITLE
Github Action fails with "Invalid or incomplete introspection result."

### ISSUE THREAD

**Issue by CelsoSantos** [kamilkisiela/graphql-inspector#2123]
**Describe the bug**

Whenever trying to use the Github Action, the jobs will fail with the following message, even though the introspection file DOES follow the rule:

```
Error: Invalid or incomplete introspection result. Ensure that you are passing "data" property of introspection response and no "errors" was returned alongside: { data: { __schema: [Object] } }.
```

**To Reproduce**
Run/Apply the configuration demonstrated on the `Environment` section and the error should be present

**Expected behavior**

Expected the process to either do nothing but exit in a success state or get a changelog if changes are present.

**Environment:**

```
  graphql-changelogs:
    name: Generate GraphQL API Changelogs
    needs: changes
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: needs.changes.outputs.graphql-api-docs == 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      # - uses: kamilkisiela/graphql-inspector@master
      #   with:
      #     name: 'Validate AC API'
      #     schema: 'master:actionable-content/ac-api/src/main/resources/graphql/schema.json'

      - name: 'Validate Notifications API'
        uses: kamilkisiela/graphql-inspector@v3.1.2
        with:
          name: 'Validate Notification API'
          schema: 'master:notification/notification-api/src/main/resources/graphql/schema.json'
```

EDIT:
Adding a screenshot of the schema file (cannot share the file though, sorry)
![Screen Shot 2022-06-30 at 11 43 41](https://user-images.githubusercontent.com/1015506/176658582-9587382c-feaf-470d-8d67-bd01d6899ec6.png)

**Comment by CelsoSantos** [comment]
no updates or possible solutions to check?

**Comment by sebj** [comment]
Seeing the same issue with a similar schema file format here, comparing local JSON schema against an endpoint.

**Comment by CelsoSantos** [comment]
- The cli works fine, either on GHA or locally.
- The Action fails with this message
- The Docker container on v3.3.0 is failling with some typescript error (it's possible I'm using it wrong)
- The GH Application seems limited to one schema..

Can we please sort this out? How can I help?

**Comment by pstarritt-evooq** [comment]
I am also experiencing this issue. Any update would be greatly appreciated

```
      - uses: kamilkisiela/graphql-inspector@master
        with:
          name: Validate GraphQL API
          schema: 'master:path/schema.json'
```

```
{
  "data": {
    "__schema": {
      "queryType": {
        "name": "Query"
      },
      "mutationType": {
        "name": "Mutation"
      },
      "subscriptionType": null,
      "types": [......],
      "directives": [.......]
  }
}
```

Query master:path/schema.json
Query refs/pull/8630/merge:path/schema.json from 
Got both sources
Error: Invalid or incomplete introspection result. Ensure that you are passing "data" property of introspection response and no "errors" was returned alongside: { data: { __schema: [Object] } }.
