### ISSUE TITLE
Github App > Diff breaks when referencing .json file

### ISSUE THREAD

**Issue by Jacob-Bordelon** [kamilkisiela/graphql-inspector#2147]
### Issue workflow progress

_Progress of the issue based on the [Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [ ] 1. The issue provides a reproduction available on GitHub, Stackblitz or CodeSandbox
> Make sure to fork this template and run `yarn generate` in the terminal.
>
> Please make sure the Codegen and plugins version under `package.json` matches yours.
- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**

In the Github app, performing the diff operation fails when the `schema` field is set to a json file in the .github/inspector.yaml file.
The following error message is received.

However, Running the graphql-inspector from the cli has no issue resolving json files.
Running the inspector from cli and referencing the file in github also succeeded.

We are unsure why referencing a json schema in the Github Application breaks when a graphql file succeeds

**To Reproduce**

*Setup*
_in the inspector configuration file_: 
1. Set the `schema` field value to `path/to/schema.json`
2. Set the `env:main:endpoint` field to your `/graphql` endpoint
... add, commit, push changes to main branch ...

*Action*
1. Open a new pull request
2. Run graphql-inspector check
3. ```Error Message: ERROR: Failed to parse "refs/pull/249/merge:docs/schema.json": Syntax Error: Expected Name, found String "__schema".```

**Expected behavior**

1. Open a new pull request
2. Run graphql-inspector check
3.
```
Detected the following changes (1) between schemas:

 Field name was removed from object type Foo
error Detected 1 breaking change
```
 *Meanwhile*
`$ graphql-inspector diff http://localhost/graphql github:org/repo#refs/pull/249/merge:docs/schema.json --token TOKEN`
Yields desired results

**Environment:**

- OS:github && MacOS
- `@graphql-inspector/...`:github app & 3.3.8
- `graphql`:N/A
- NodeJS:8.13.2

**Additional context**

__inspector.yaml__
```
diff:
  summaryLimit: 900
schema: './schema.json'
env:
  main:
    branch: 'main'
    endpoint: 'http://main.aws.rds.server/graphql'
  staging:
    branch: 'staging'
    endpoint: 'http://staging.aws.rds.server/graphql'
notifications:
  slack: 'https://hooks.slack.com/services/path/to/slack/hook'

```

__schema.json__
```
{
    "__schema": {
        "queryType": {
            "name": "Query"
        },
        "mutationType": {
            "name": "Mutations"
        },
        "subscriptionType": null,
        "types": [
            {
                "kind": "OBJECT",
                "name": "Query",
                "description": null,
                "fields": [
                    {
          ...
```
