### ISSUE TITLE
405 When use Github Actions

### ISSUE THREAD

**Issue by rdp77** [kamilkisiela/graphql-inspector#2171]
```
- name: Test GraphQL with GraphiQL Inspector
        uses: kamilkisiela/graphql-inspector@master
        with:
          schema: 'https://.../graphql'
          endpoint: 'https://.../graphql'
```

```
Run kamilkisiela/graphql-inspector@master
GraphQL Inspector started
Ref: 1e7f27563[13](https://github.com/mataharilabs/asiacommerce-client-management/runs/8285303538?check_suite_focus=true#step:15:14)7685a1a4ed5902633e4ee71355356
Commit SHA: 1e7f27563137685a1a4ed5902633e4ee71355356
Creating a check named "GraphQL Inspector"
Check ID: 8285313035
EXPERIMENTAL - Using Pull Request refs/pull/3277/merge
EXPERIMENTAL - Using staging-dev as base schema ref
Error: Request failed with status code 405
```

https://www.the-guild.dev/graphql/inspector/docs/products/action#endpoint
