### ISSUE TITLE
Github Actions Not Work

### ISSUE THREAD

**Issue by rdp77** [kamilkisiela/graphql-inspector#2172]
I use [Lighthouse](https://github.com/nuwave/lighthouse)

```
 - name: Test GraphQL with GraphiQL Inspector
        uses: kamilkisiela/graphql-inspector@master
        with:
          schema: 'staging-dev:graphql/schema.graphql'
```

```
Run kamilkisiela/graphql-inspector@master
GraphQL Inspector started
Ref: b56be3e8f0598365bb[26](https://github.com/.../runs/8285303538?check_suite_focus=true#step:12:27)e8457d9e0da4ad8d33d4
Commit SHA: b56be3e8f0598365bb26e8457d9e0da4ad8d33d4
Creating a check named "GraphQL Inspector"
Check ID: 8283028754
Query staging-dev:graphql/schema.graphql from repo
Got both sources
Built both schemas
Start comparing schemas

Changes: 0
Conclusion: success
Updating check: 8283028754
annotations to be sent: 0
annotations sent (0)
```

It's weird is there something wrong with my configuration, the inspector doesn't give any feedback except
Conclusion: success
Updating check: 8283028754

https://www.the-guild.dev/graphql/inspector/docs/products/action#usage
