### ISSUE TITLE
Github Action Deprecation notices

### ISSUE THREAD

**Issue by jameslnewell** [kamilkisiela/graphql-inspector#2196]
### Issue workflow progress

_Progress of the issue based on the
[Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [ ] 1. The issue provides a reproduction available on GitHub, Stackblitz or CodeSandbox
     > Make sure to fork this template and run `yarn generate` in the terminal.
     >
     > Please make sure the Codegen and plugins version under `package.json` matches yours.
- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**

Github Actions are reporting some impending deprecations and changes that could affect functionality.

```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: kamilkisiela/graphql-inspector
```

```
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

**To Reproduce** Steps to reproduce the behavior:

Add the action to a workflow
```yml
name: Check GraphQL Schema

on:
  pull_request:
    branches:
      - main

jobs:
  check-graphql-schema:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        
      - uses: kamilkisiela/graphql-inspector@v3.4.0
        with:
          schema: 'main:schema.graphql'

```

**Expected behavior**

Deprecations don't show

**Environment:**

- OS: `ubuntu-latest`
- `@graphql-inspector/...`: 3.4.0
- `graphql`: -
- NodeJS: 12

**Additional context**
