### ISSUE TITLE
Github Action should allow rules to be applied

### ISSUE THREAD

**Issue by Tohaker** [kamilkisiela/graphql-inspector#2250]
**Is your feature request related to a problem? Please describe.**

Just like how the CLI can accept a list of rules (both built-in and custom), so too should the Action allow for these same rules to be applied to the resulting diff.

**Describe the solution you'd like**

```yml
- uses: kamilkisiela/graphql-inspector@master
  with:
    schema: 'master:schema.graphql'
    rules:
      - suppressRemovalOfDeprecatedField
      - './custom-rule.js'
```
**Describe alternatives you've considered**

Using the CLI in CI is fine, but doesn't give the rich output of the action
