### ISSUE TITLE
Resource not accessible by integration

### ISSUE THREAD

**Issue by leonard-henriquez** [kamilkisiela/graphql-inspector#2672]
### Issue workflow progress

_Progress of the issue based on the
[Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [ ] 1. The issue provides a reproduction available on GitHub, Stackblitz or CodeSandbox
     > Make sure to fork this template and run `pnpm generate` in the terminal.
     >
     > Please make sure the Codegen and plugins version under `package.json` matches yours.
- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**

When we run the github action we get the error: "Resource not accessible by integration"
![Screenshot 2023_12_05_000213](https://github.com/kamilkisiela/graphql-inspector/assets/30215564/7b4beb4f-b650-4d49-aa58-6182af60228b)

**To Reproduce** Steps to reproduce the behavior:

Our `.github/workflows/continuous_integration.yml`

```
name: continuous_integration
on:
  push:
    branches:
      - main
      - staging

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  breaking_changes_graphql:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install dependencies
        uses: ./.github/actions/pnpm-install-action

      - uses: kamilkisiela/graphql-inspector@master
        with:
          schema: 'main:schema.graphql'
```

**Expected behavior**

I would expect the github action to finish with a report

**Environment:**

- OS: ubuntu
- `graphql-inspector@master`

**Additional context**

**Comment by leonard-henriquez** [comment]
@kamilkisiela is this repo still under active maintenance ?

**Comment by kamilkisiela** [comment]
[Yes](https://github.com/kamilkisiela/graphql-inspector/commits/master/)

**Comment by leonard-henriquez** [comment]
Awesome !
@kamilkisiela Do you have any idea what this error mean?
I can't find this message in this codebase.
I have no clue how to debug this error...

**Comment by leonard-henriquez** [comment]
It works when I add all permissions.
Any ideas what are the ones needed ?
![Screenshot 2023_12_13_000239](https://github.com/kamilkisiela/graphql-inspector/assets/30215564/5fa99c75-b92f-4e42-92be-cac23f027013)

**Comment by ljukas** [comment]
![image](https://github.com/kamilkisiela/graphql-inspector/assets/11976354/f1b9c42c-e915-4b26-b34c-f7f0973a775f)
Mine looks like this and gets the same error.  I have set check to write as the docs say here:
![image](https://github.com/kamilkisiela/graphql-inspector/assets/11976354/18b367b7-cc68-4388-aa02-62a9297ab8ba)

Will have to go through and enable each one to see which stops this from working

**Comment by billdybas** [comment]
I think you also need the `pull-requests: read` permission. I ran into the same issue & traced it back to `getAssociatedPullRequest` failing.

https://github.com/kamilkisiela/graphql-inspector/blob/e77738accd6406e83f4376d86e87f87ffd0effd0/packages/action/src/run.ts#L51

It [makes an API call](https://github.com/kamilkisiela/graphql-inspector/blob/e77738accd6406e83f4376d86e87f87ffd0effd0/packages/action/src/git.ts#L27) to [`GET /repos/{owner}/{repo}/commits/{commit_sha}/pulls`](https://docs.github.com/en/rest/commits/commits?apiVersion=2022-11-28#list-pull-requests-associated-with-a-commit) which [requires `read` permissions](https://docs.github.com/en/rest/authentication/permissions-required-for-github-apps?apiVersion=2022-11-28#repository-permissions-for-pull-requests) on pull requests.

**Comment by glg-satish-tripathi** [comment]
@leonard-henriquez After thorough investigation, I discovered that this is the bare minimum permission required for the action to run. 

```
permissions:
  contents: read 
  pull-requests: read
  checks: write
 ```
